services:
  app:
    image: lscr.io/linuxserver/duckdns:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=jzoidberg
      - TOKEN=3a1a4575-0490-4745-bf35-b2d6d52b7421
    restart: on-failure
icon: https://raw.githubusercontent.com/tu-usuario/francesc-umbrel-apps/main/francesc-duckdns/icon.png
